### ISSUE TITLE
API was changed between patch version

### ISSUE THREAD

**Issue by rur** [pape-io/browser-detection#3]
There was a breaking API change in  8850969b77d3f9b02542fe90bcf43f3da96aedf2 and it resulted in a mere patch version bump in the following baebb692be629fa5be89f1b1f5e17fc55c8abc78 

API changes should only be changed between major revisions. This caused a completely unexpected breakage.

At the very least, a new patch version (1.0.3) needs be created that restores the API. If you *must* remove 'isSupported' prepare a 2.0 release

**Comment by pape-io** [comment]
Im sorry and thanks for pointing out!

Created https://github.com/pape-io/browser-detection/releases/tag/1.0.3 for you.

And a clean 2.0.0 https://github.com/pape-io/browser-detection/releases/tag/2.0.0.

I hope that fixes your problem. Otherwise just tell me ;)

**Comment by rur** [comment]
Thanks for the quick response!
